// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtjwodwzjwgebhnsergv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0andvZHd6andnZWJobnNlcmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MTA3NTYsImV4cCI6MjA1NDM4Njc1Nn0.gDAmpS4IMHjFHEzRnOL59DpeklsPn0VUrrcvewlBvZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);